name: CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t openzim/zimit:dev .

      - name: run crawl
        run: docker run -it -v $PWD/output:/output openzim/zimit:dev zimit --url https://isago.ml/ --name isago --zim-file isago.zim

      - name: ensure zim exists
        run: stat ./output/isago.zim
